const INVALID_INPUT = 'INVALID_INPUT';
const INVALID_COMMAND = 'INVALID_COMMAND';
const COMMAND_FAILED = 'COMMAND_FAILED';
const NO_SUCH_TRAINEE = 'NO_SUCH_TRAINEE';

export default {
  INVALID_INPUT,
  INVALID_COMMAND,
  COMMAND_FAILED,
  NO_SUCH_TRAINEE,
};
